apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: rmq-1
  description: VMware Tanzu RabbitMQ messaging systems for asynchronous messaging
spec:
  type: messaging-system
  owner: team-vmware-tanzu-se
  system: ride-app-system