apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: ride-app-location
  description: TAP Camunda Ride App
  annotations:
    'backstage.io/techdocs-ref': dir:.
spec:
  targets:
    - ./systems/ride-app-system.yaml
    - ./components/service/high-mobility-source-component.yaml
    - ./components/service/ride-service-component.yaml
    - ./components/service/zeebe-event-bridge-component.yaml
    - ./components/service/camunda-process-deployer-component.yaml
    - ./components/service/driver-match-service-component.yaml
    - ./components/service/payment-service-component.yaml
    - ./components/service/invoice-service-component.yaml
    - ./components/service/get-drivers-service-component.yaml
    - ./groups/department.yaml
    - ./groups/org.yaml
    - ./groups/team.yaml
    - ./resources/auth-server-resource.yaml
    - ./resources/config-server-resource.yaml
    - ./resources/rabbit-resource.yaml
    - ./resources/postgres-resource.yaml