apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: ride-app-system
  description: TAP Camunda Ride App
  annotations:
    'backstage.io/techdocs-ref': dir:.
spec:
  owner: team-vmware-tanzu-se