apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rmq-1
spec:
  imagePullSecrets:
    - name: tap-registry
  persistence:
    storage: 5Gi
  rabbitmq:
    additionalPlugins:
    - rabbitmq_stream
    - rabbitmq_web_mqtt