apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: invoice-service
  annotations:
    autoscaling.knative.dev/min-scale: "1"
  labels:
    app.kubernetes.io/part-of: invoice-service
    apps.tanzu.vmware.com/workload-type: queue
    apps.tanzu.vmware.com/has-tests: true
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"
  source:
    git:
      url: https://github.com/tsalm-pivotal/tap-camunda-ride-app
      ref:
        branch: main
  #    subPath: high-mobility-source
  serviceClaims:
    - name: config-server
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ResourceClaim
        name: configserver-binding-compatible