apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: high-mobility-source
  annotations:
    autoscaling.knative.dev/min-scale: "1"
  labels:
    app.kubernetes.io/part-of: high-mobility-source
    apps.tanzu.vmware.com/workload-type: web
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"
  source:
    git:
      url: https://github.com/tsalm-pivotal/tap-camunda-ride-app
      ref:
        branch: main
#    subPath: high-mobility-source